#!/bin/sh

### Vars
LED_GPTIO1=43 # HDD 1
LED_GPTIO2=52 # HDD 2
#LED_GPTIO3=00 # Power

### Functions
init_gpio () {
	if [ ! -d /sys/class/gpio/gpio$1/ ]; then
		echo $1 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio$1/direction
	fi
}

change_state () {
	case "$2" in
		"on" ) echo 1 > /sys/class/gpio/gpio$1/value ;;
		"off" ) echo 0 > /sys/class/gpio/gpio$1/value ;;
		"blink" )
			# echo 1 > /sys/class/gpio/gpio$1/value
			echo "Blinking led not realized"
		;;
		* )
			echo 0 > /sys/class/gpio/gpio$1/value
			# TODO: disable blinking
		;;
	esac
}

### Logic
if [ $# -ne 2 ]; then
	echo "Usage: led <hdd1/hdd2/power> <on/off/blink>"
	exit 1
fi

init_gpio $LED_GPTIO1
init_gpio $LED_GPTIO2

case "$1" in
	"hdd1" ) change_state $LED_GPTIO1 $2 ;;
	"hdd2" ) change_state $LED_GPTIO2 $2 ;;
	"power" ) echo "power led not realized" ;;
esac
