#!/bin/busybox ash
# init-script for WD Mycloud Mirror gen2 & Ex2 ultra
# Boots from partition labeled "rootfs"
# (c) Carl Schiller; schreibcarl@gmail.com

#-----------functions--------------
# Start decryption filesystem
decrypt_shell() {
  # Check which device encrypted
  export cryptdev=$(blkid -l -o device -t TYPE=crypto_LUKS)
  echo device=$(blkid -l -o device -t TYPE=crypto_LUKS) >>/etc/profile      # add location of crytodevice to environment
  echo export device >>/etc/profile
  # Look for key on usb / hdd
  mount -o rw $(findfs LABEL=key) /mnt/key
  wait
  if [  -e /mnt/key/key.luks  ]; then
    cryptsetup luksOpen $cryptdev cryptroot --key-file /mnt/key/key.luks
    check_unlock
  else
    startnetwork
    dropbear -B -p 2222 -b /etc/dropbear/banner.crypto -P /run/dropbear.pid 2>&1 >/dev/null
  fi
}

# Check if key-decrypt was sucessfull
check_unlock(){
wait    
if ! [ -e /dev/mapper/cryptroot ]; then
    echo -e "Unlock check failed,..."
    rescue_shell
fi
}

# setting up network
startnetwork() {
  /sbin/getmac
  ifconfig eth0 up
  udhcpc -t 5 -q -s /bin/simple.script -p /run/udhcpc.pid
}

# rescue_shell
rescue_shell() {
# start ssh
startnetwork
dropbear -B -p 2222 -b /etc/dropbear/banner.rescue -P /run/dropbear.pid 2>&1 >/dev/null
echo -e "\n Something went wrong. Dropping to a shell.\n"

  # Run UART shell
  exec 0</dev/console
  exec 1>/dev/console
  exec 2>/dev/console
  exec setsid cttyhack /bin/ash
}

#LVM init sequence
initlvm() {
  lvm vgscan --mknodes # creates /dev/mapper/control
  lvm vgchange -a ly
  lvm vgscan --mknodes # creates /dev/mapper/VG-root and /dev/VG/root
  wait
}

#Switchroot seqence
boot() {
  echo -e "\n Unmounting and Switch to OS\n"
  wait
  # kill running daemons
  [ -r "/run/dropbear.pid" ] && kill -9 $(cat /run/dropbear.pid)
  [ -r "/run/udhcpc.pid" ]   && kill -9 $(cat /run/udhcpc.pid)
  umount /mnt/config 2> /dev/null
  umount /sys 2> /dev/null
  umount /proc 2> /dev/null
  umount /dev/pts 2> /dev/null
  umount /dev 2> /dev/null
  exec switch_root -c /dev/console /mnt/root /sbin/init
}

#-----------init script--------------
# Creat folders and install Busybox
/bin/busybox mkdir -p /dev /mnt/root /mnt/key /mnt/config /mnt/config/initrd /proc /root /usr/sbin /usr/bin /sbin /bin /sys /run
/bin/busybox --install -s

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Adding mdev support
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

# Initial Raid
echo 'DEVICE /dev/sd??*' >/etc/mdadm.conf
mdadm -Eb /dev/sd??* >>/etc/mdadm.conf
mdadm -As --force
wait # disk not ready?
mdadm --assemble --scan

# Mount the config files
ubiattach /dev/ubi_ctrl -m 5
wait
mount -t ubifs ubi0:config /mnt/config

#check for LUKS-devices
decrypt_shell
echo -e "\n Waiting for device decryption"
# wait until the device exists and is decrypted
while ! [ -e /dev/mapper/cryptroot ]; do
  sleep 2
done

initlvm
mount -o rw /dev/MyVolGroup/root /mnt/root 2>&1 >/dev/null
if [ -h /mnt/root/sbin/init -o -e /mnt/root/sbin/init ]; then
  boot
else
  rescue_shell
fi
